//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace cf.Entities
{
    public partial class ClimbIndoor : Climb
    {
        #region Primitive Properties
    
        public virtual bool SetterAnonymous
        {
            get;
            set;
        }
    
        public virtual byte ClimbTypeID
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> SetDate
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> DiscontinuedDate
        {
            get;
            set;
        }
    
        public virtual string MarkingColor
        {
            get;
            set;
        }
    
        public virtual Nullable<byte> MarkingType
        {
            get;
            set;
        }
    
        public virtual string LineNumber
        {
            get;
            set;
        }

        #endregion
        #region Association Fixup
    
        private bool _settingFK = false;

        #endregion
    }
}
