//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace cf.Entities
{
    public partial class ClimbOutdoor : Climb
    {
        #region Primitive Properties
    
        public virtual byte ClimbTypeID
        {
            get;
            set;
        }
    
        public virtual byte ClimbTerrainID
        {
            get;
            set;
        }
    
        public virtual int NumberOfPitches
        {
            get;
            set;
        }
    
        public virtual Nullable<System.Guid> ParentID
        {
            get;
            set;
        }
    
        public virtual string DescriptionWhere
        {
            get;
            set;
        }
    
        public virtual string DescriptionStart
        {
            get;
            set;
        }
    
        public virtual string DescriptionGear
        {
            get;
            set;
        }
    
        public virtual string DescriptionSafety
        {
            get;
            set;
        }
    
        public virtual string SafetyRating
        {
            get;
            set;
        }
    
        public virtual byte LocationPostionIndex
        {
            get;
            set;
        }

        #endregion
        #region Association Fixup
    
        private bool _settingFK = false;

        #endregion
    }
}
