//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace cf.Entities
{
    public partial class ConversationView
    {
        #region Primitive Properties
    
        public virtual System.Guid ID
        {
            get;
            set;
        }
    
        public virtual System.Guid PartyID
        {
            get;
            set;
        }
    
        public virtual System.Guid ConversationID
        {
            get { return _conversationID; }
            set
            {
                if (_conversationID != value)
                {
                    if (Conversation != null && Conversation.ID != value)
                    {
                        Conversation = null;
                    }
                    _conversationID = value;
                }
            }
        }
        private System.Guid _conversationID;
    
        public virtual byte Status
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual Conversation Conversation
        {
            get { return _conversation; }
            set
            {
                if (!ReferenceEquals(_conversation, value))
                {
                    var previousValue = _conversation;
                    _conversation = value;
                    FixupConversation(previousValue);
                }
            }
        }
        private Conversation _conversation;

        #endregion
        #region Association Fixup
    
        private void FixupConversation(Conversation previousValue)
        {
            if (previousValue != null && previousValue.ConversationViews.Contains(this))
            {
                previousValue.ConversationViews.Remove(this);
            }
    
            if (Conversation != null)
            {
                if (!Conversation.ConversationViews.Contains(this))
                {
                    Conversation.ConversationViews.Add(this);
                }
                if (ConversationID != Conversation.ID)
                {
                    ConversationID = Conversation.ID;
                }
            }
        }

        #endregion
    }
}
