//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace cf.Entities
{
    public partial class LocationOutdoor : LocationEF
    {
        #region Primitive Properties
    
        public virtual string AccessIssues
        {
            get;
            set;
        }
    
        public virtual Nullable<bool> ClimbingWinterAM
        {
            get;
            set;
        }
    
        public virtual Nullable<bool> ClimbingWinterPM
        {
            get;
            set;
        }
    
        public virtual Nullable<bool> ClimbingSummerAM
        {
            get;
            set;
        }
    
        public virtual Nullable<bool> ClimbingSummerPM
        {
            get;
            set;
        }
    
        public virtual string Cautions
        {
            get;
            set;
        }
    
        public virtual int Altitude
        {
            get;
            set;
        }
    
        public virtual bool AccessClosed
        {
            get;
            set;
        }
    
        public virtual string Approach
        {
            get;
            set;
        }
    
        public virtual Nullable<bool> ShadeMorning
        {
            get;
            set;
        }
    
        public virtual Nullable<bool> ShadeMidday
        {
            get;
            set;
        }
    
        public virtual Nullable<bool> ShadeAfternoon
        {
            get;
            set;
        }

        #endregion
    }
}
