//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace cf.Entities
{
    public partial class MediaOpinion
    {
        #region Primitive Properties
    
        public virtual System.Guid ID
        {
            get;
            set;
        }
    
        public virtual System.Guid MediaID
        {
            get { return _mediaID; }
            set
            {
                if (_mediaID != value)
                {
                    if (Medium != null && Medium.ID != value)
                    {
                        Medium = null;
                    }
                    _mediaID = value;
                }
            }
        }
        private System.Guid _mediaID;
    
        public virtual System.Guid UserID
        {
            get { return _userID; }
            set
            {
                if (_userID != value)
                {
                    if (Profile != null && Profile.ID != value)
                    {
                        Profile = null;
                    }
                    _userID = value;
                }
            }
        }
        private System.Guid _userID;
    
        public virtual byte Rating
        {
            get;
            set;
        }
    
        public virtual string Comment
        {
            get;
            set;
        }
    
        public virtual System.DateTime Utc
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual Media Medium
        {
            get { return _medium; }
            set
            {
                if (!ReferenceEquals(_medium, value))
                {
                    var previousValue = _medium;
                    _medium = value;
                    FixupMedium(previousValue);
                }
            }
        }
        private Media _medium;
    
        public virtual Profile Profile
        {
            get { return _profile; }
            set
            {
                if (!ReferenceEquals(_profile, value))
                {
                    var previousValue = _profile;
                    _profile = value;
                    FixupProfile(previousValue);
                }
            }
        }
        private Profile _profile;

        #endregion
        #region Association Fixup
    
        private void FixupMedium(Media previousValue)
        {
            if (previousValue != null && previousValue.MediaOpinions.Contains(this))
            {
                previousValue.MediaOpinions.Remove(this);
            }
    
            if (Medium != null)
            {
                if (!Medium.MediaOpinions.Contains(this))
                {
                    Medium.MediaOpinions.Add(this);
                }
                if (MediaID != Medium.ID)
                {
                    MediaID = Medium.ID;
                }
            }
        }
    
        private void FixupProfile(Profile previousValue)
        {
            if (previousValue != null && previousValue.MediaOpinions.Contains(this))
            {
                previousValue.MediaOpinions.Remove(this);
            }
    
            if (Profile != null)
            {
                if (!Profile.MediaOpinions.Contains(this))
                {
                    Profile.MediaOpinions.Add(this);
                }
                if (UserID != Profile.ID)
                {
                    UserID = Profile.ID;
                }
            }
        }

        #endregion
    }
}
