//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace cf.Entities
{
    public partial class PartnerCallNotificationWorkItem
    {
        #region Primitive Properties
    
        public virtual System.Guid ID
        {
            get;
            set;
        }
    
        public virtual System.Guid PartnerCallID
        {
            get;
            set;
        }
    
        public virtual byte CountryID
        {
            get;
            set;
        }
    
        public virtual System.Guid PlaceID
        {
            get;
            set;
        }
    
        public virtual System.Guid OnBehalfOfUserID
        {
            get;
            set;
        }
    
        public virtual System.DateTime CreatedUtc
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> ProcessedUtc
        {
            get;
            set;
        }
    
        public virtual int NotificationsSent
        {
            get;
            set;
        }
    
        public virtual int ReplyCount
        {
            get;
            set;
        }

        #endregion
    }
}
