//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace cf.Entities
{
    public partial class PartnerCallSubscription
    {
        #region Primitive Properties
    
        public virtual System.Guid ID
        {
            get;
            set;
        }
    
        public virtual System.Guid UserID
        {
            get { return _userID; }
            set
            {
                if (_userID != value)
                {
                    if (Profile != null && Profile.ID != value)
                    {
                        Profile = null;
                    }
                    _userID = value;
                }
            }
        }
        private System.Guid _userID;
    
        public virtual System.Guid PlaceID
        {
            get;
            set;
        }
    
        public virtual System.DateTime CreatedUtc
        {
            get;
            set;
        }
    
        public virtual bool ForIndoor
        {
            get;
            set;
        }
    
        public virtual bool ForOutdoor
        {
            get;
            set;
        }
    
        public virtual bool EmailRealTime
        {
            get;
            set;
        }
    
        public virtual bool MobileRealTime
        {
            get;
            set;
        }
    
        public virtual bool ExactMatchOnly
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual Profile Profile
        {
            get { return _profile; }
            set
            {
                if (!ReferenceEquals(_profile, value))
                {
                    var previousValue = _profile;
                    _profile = value;
                    FixupProfile(previousValue);
                }
            }
        }
        private Profile _profile;

        #endregion
        #region Association Fixup
    
        private void FixupProfile(Profile previousValue)
        {
            if (previousValue != null && previousValue.PartnerCallSubscriptions.Contains(this))
            {
                previousValue.PartnerCallSubscriptions.Remove(this);
            }
    
            if (Profile != null)
            {
                if (!Profile.PartnerCallSubscriptions.Contains(this))
                {
                    Profile.PartnerCallSubscriptions.Add(this);
                }
                if (UserID != Profile.ID)
                {
                    UserID = Profile.ID;
                }
            }
        }

        #endregion
    }
}
