//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace cf.Entities
{
    public partial class PartnerCall
    {
        #region Primitive Properties
    
        public virtual System.Guid ID
        {
            get;
            set;
        }
    
        public virtual System.Guid UserID
        {
            get { return _userID; }
            set
            {
                if (_userID != value)
                {
                    if (Profile != null && Profile.ID != value)
                    {
                        Profile = null;
                    }
                    _userID = value;
                }
            }
        }
        private System.Guid _userID;
    
        public virtual System.Guid PlaceID
        {
            get;
            set;
        }
    
        public virtual bool ForIndoor
        {
            get;
            set;
        }
    
        public virtual bool ForOutdoor
        {
            get;
            set;
        }
    
        public virtual System.DateTime CreatedUtc
        {
            get;
            set;
        }
    
        public virtual System.DateTime StartDateTime
        {
            get;
            set;
        }
    
        public virtual System.DateTime EndDateTime
        {
            get;
            set;
        }
    
        public virtual byte PreferredLevel
        {
            get;
            set;
        }
    
        public virtual bool UserDeleted
        {
            get;
            set;
        }
    
        public virtual string Comment
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<PartnerCallReply> PartnerCallReplys
        {
            get
            {
                if (_partnerCallReplys == null)
                {
                    var newCollection = new FixupCollection<PartnerCallReply>();
                    newCollection.CollectionChanged += FixupPartnerCallReplys;
                    _partnerCallReplys = newCollection;
                }
                return _partnerCallReplys;
            }
            set
            {
                if (!ReferenceEquals(_partnerCallReplys, value))
                {
                    var previousValue = _partnerCallReplys as FixupCollection<PartnerCallReply>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupPartnerCallReplys;
                    }
                    _partnerCallReplys = value;
                    var newValue = value as FixupCollection<PartnerCallReply>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupPartnerCallReplys;
                    }
                }
            }
        }
        private ICollection<PartnerCallReply> _partnerCallReplys;
    
        public virtual Profile Profile
        {
            get { return _profile; }
            set
            {
                if (!ReferenceEquals(_profile, value))
                {
                    var previousValue = _profile;
                    _profile = value;
                    FixupProfile(previousValue);
                }
            }
        }
        private Profile _profile;

        #endregion
        #region Association Fixup
    
        private void FixupProfile(Profile previousValue)
        {
            if (previousValue != null && previousValue.PartnerCalls.Contains(this))
            {
                previousValue.PartnerCalls.Remove(this);
            }
    
            if (Profile != null)
            {
                if (!Profile.PartnerCalls.Contains(this))
                {
                    Profile.PartnerCalls.Add(this);
                }
                if (UserID != Profile.ID)
                {
                    UserID = Profile.ID;
                }
            }
        }
    
        private void FixupPartnerCallReplys(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (PartnerCallReply item in e.NewItems)
                {
                    item.PartnerCall = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (PartnerCallReply item in e.OldItems)
                {
                    if (ReferenceEquals(item.PartnerCall, this))
                    {
                        item.PartnerCall = null;
                    }
                }
            }
        }

        #endregion
    }
}
