//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace cf.Entities
{
    public partial class PlaceBingMapView
    {
        #region Primitive Properties
    
        public virtual System.Guid ID
        {
            get;
            set;
        }
    
        public virtual string Bounds
        {
            get;
            set;
        }
    
        public virtual string CenterOffset
        {
            get;
            set;
        }
    
        public virtual string Heading
        {
            get;
            set;
        }
    
        public virtual string MapCenterLatitude
        {
            get;
            set;
        }
    
        public virtual string MapCenterLongitude
        {
            get;
            set;
        }
    
        public virtual string MapTypeId
        {
            get;
            set;
        }
    
        public virtual string Zoom
        {
            get;
            set;
        }

        #endregion
    }
}
