//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace cf.Entities
{
    public partial class UserPersonalityMedia
    {
        #region Primitive Properties
    
        public virtual System.Guid ID
        {
            get;
            set;
        }
    
        public virtual System.Guid UserID
        {
            get { return _userID; }
            set
            {
                if (_userID != value)
                {
                    if (Profile != null && Profile.ID != value)
                    {
                        Profile = null;
                    }
                    _userID = value;
                }
            }
        }
        private System.Guid _userID;
    
        public virtual System.Guid MediaID
        {
            get { return _mediaID; }
            set
            {
                if (_mediaID != value)
                {
                    if (Media != null && Media.ID != value)
                    {
                        Media = null;
                    }
                    _mediaID = value;
                }
            }
        }
        private System.Guid _mediaID;
    
        public virtual byte CategoryID
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual Media Media
        {
            get { return _media; }
            set
            {
                if (!ReferenceEquals(_media, value))
                {
                    var previousValue = _media;
                    _media = value;
                    FixupMedia(previousValue);
                }
            }
        }
        private Media _media;
    
        public virtual Profile Profile
        {
            get { return _profile; }
            set
            {
                if (!ReferenceEquals(_profile, value))
                {
                    var previousValue = _profile;
                    _profile = value;
                    FixupProfile(previousValue);
                }
            }
        }
        private Profile _profile;

        #endregion
        #region Association Fixup
    
        private void FixupMedia(Media previousValue)
        {
            if (previousValue != null && previousValue.UserPersonalityMedias.Contains(this))
            {
                previousValue.UserPersonalityMedias.Remove(this);
            }
    
            if (Media != null)
            {
                if (!Media.UserPersonalityMedias.Contains(this))
                {
                    Media.UserPersonalityMedias.Add(this);
                }
                if (MediaID != Media.ID)
                {
                    MediaID = Media.ID;
                }
            }
        }
    
        private void FixupProfile(Profile previousValue)
        {
            if (previousValue != null && previousValue.UserPersonalityMedias.Contains(this))
            {
                previousValue.UserPersonalityMedias.Remove(this);
            }
    
            if (Profile != null)
            {
                if (!Profile.UserPersonalityMedias.Contains(this))
                {
                    Profile.UserPersonalityMedias.Add(this);
                }
                if (UserID != Profile.ID)
                {
                    UserID = Profile.ID;
                }
            }
        }

        #endregion
    }
}
