//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.EntityClient;

namespace cf.DataAccess.EntityFramework
{
    public partial class cfEntitiesData : ObjectContext
    {
        public const string ConnectionString = "name=cfEntitiesData";
        public const string ContainerName = "cfEntitiesData";
    
        #region Constructors
    
        public cfEntitiesData()
            : base(ConnectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public cfEntitiesData(string connectionString)
            : base(connectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public cfEntitiesData(EntityConnection connection)
            : base(connection, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        #endregion
    
        #region ObjectSet Properties
    
        public ObjectSet<cf.Entities.PostComment> PostComments
        {
            get { return _postComments  ?? (_postComments = CreateObjectSet<cf.Entities.PostComment>("PostComments")); }
        }
        private ObjectSet<cf.Entities.PostComment> _postComments;
    
        public ObjectSet<cf.Entities.Post> Posts
        {
            get { return _posts  ?? (_posts = CreateObjectSet<cf.Entities.Post>("Posts")); }
        }
        private ObjectSet<cf.Entities.Post> _posts;

        public ObjectSet<cf.Entities.LocationEF> Locations
        {
            get { return _locations ?? (_locations = CreateObjectSet<cf.Entities.LocationEF>("LocationEFs")); }
        }
        private ObjectSet<cf.Entities.LocationEF> _locations;
    
        public ObjectSet<cf.Entities.Profile> Profiles
        {
            get { return _profiles  ?? (_profiles = CreateObjectSet<cf.Entities.Profile>("Profiles")); }
        }
        private ObjectSet<cf.Entities.Profile> _profiles;
    
        public ObjectSet<cf.Entities.ModAction> ModActions
        {
            get { return _modActions  ?? (_modActions = CreateObjectSet<cf.Entities.ModAction>("ModActions")); }
        }
        private ObjectSet<cf.Entities.ModAction> _modActions;
    
        public ObjectSet<cf.Entities.ModProfile> ModProfiles
        {
            get { return _modProfiles  ?? (_modProfiles = CreateObjectSet<cf.Entities.ModProfile>("ModProfiles")); }
        }
        private ObjectSet<cf.Entities.ModProfile> _modProfiles;
    
        public ObjectSet<cf.Entities.PlaceBingMapView> PlaceBingMapViews
        {
            get { return _placeBingMapViews  ?? (_placeBingMapViews = CreateObjectSet<cf.Entities.PlaceBingMapView>("PlaceBingMapViews")); }
        }
        private ObjectSet<cf.Entities.PlaceBingMapView> _placeBingMapViews;
    
        public ObjectSet<cf.Entities.CheckIn> CheckIns
        {
            get { return _checkIns  ?? (_checkIns = CreateObjectSet<cf.Entities.CheckIn>("CheckIns")); }
        }
        private ObjectSet<cf.Entities.CheckIn> _checkIns;

        public ObjectSet<cf.Entities.ClimbTag> ClimbTags
        {
            get { return _climbCategories ?? (_climbCategories = CreateObjectSet<cf.Entities.ClimbTag>("ClimbTags")); }
        }
        private ObjectSet<cf.Entities.ClimbTag> _climbCategories;
    
        public ObjectSet<cf.Entities.Media> Medias
        {
            get { return _medias  ?? (_medias = CreateObjectSet<cf.Entities.Media>("Medias")); }
        }
        private ObjectSet<cf.Entities.Media> _medias;
    
        public ObjectSet<cf.Entities.ObjectMedia> ObjectMedias
        {
            get { return _objectMedias  ?? (_objectMedias = CreateObjectSet<cf.Entities.ObjectMedia>("ObjectMedias")); }
        }
        private ObjectSet<cf.Entities.ObjectMedia> _objectMedias;

        public ObjectSet<cf.Entities.MediaOpinion> MediaOpinions
        {
            get { return _mediaRatings ?? (_mediaRatings = CreateObjectSet<cf.Entities.MediaOpinion>("MediaOpinion")); }
        }
        private ObjectSet<cf.Entities.MediaOpinion> _mediaRatings;
    
        public ObjectSet<cf.Entities.Climb> Climbs
        {
            get { return _climbs  ?? (_climbs = CreateObjectSet<cf.Entities.Climb>("Climbs")); }
        }
        private ObjectSet<cf.Entities.Climb> _climbs;

        public ObjectSet<cf.Entities.LoggedClimb> LoggedClimbs
        {
            get { return _loggedClimbs ?? (_loggedClimbs = CreateObjectSet<cf.Entities.LoggedClimb>("LoggedClimbs")); }
        }
        private ObjectSet<cf.Entities.LoggedClimb> _loggedClimbs;

        public ObjectSet<cf.Entities.ModClaim> ModClaims
        {
            get { return _modClaims  ?? (_modClaims = CreateObjectSet<cf.Entities.ModClaim>("ModClaims")); }
        }
        private ObjectSet<cf.Entities.ModClaim> _modClaims;
    
        public ObjectSet<cf.Entities.ObjectModMeta> ObjectModMetas
        {
            get { return _objectModMetas  ?? (_objectModMetas = CreateObjectSet<cf.Entities.ObjectModMeta>("ObjectModMetas")); }
        }
        private ObjectSet<cf.Entities.ObjectModMeta> _objectModMetas;
    
        public ObjectSet<cf.Entities.UserPersonalityMedia> UserPersonalityMedias
        {
            get { return _userPersonalityMedias  ?? (_userPersonalityMedias = CreateObjectSet<cf.Entities.UserPersonalityMedia>("UserPersonalityMedias")); }
        }
        private ObjectSet<cf.Entities.UserPersonalityMedia> _userPersonalityMedias;

        public ObjectSet<cf.Entities.Conversation> Conversations
        {
            get { return _conversations ?? (_conversations = CreateObjectSet<cf.Entities.Conversation>("Conversations")); }
        }
        private ObjectSet<cf.Entities.Conversation> _conversations;

        public ObjectSet<cf.Entities.ConversationView> ConversationViews
        {
            get { return _conversationViews ?? (_conversationViews = CreateObjectSet<cf.Entities.ConversationView>("ConversationViews")); }
        }
        private ObjectSet<cf.Entities.ConversationView> _conversationViews;

        public ObjectSet<cf.Entities.MessagePartyStatus> MessagePartyStatus1
        {
            get { return _messagePartyStatus1 ?? (_messagePartyStatus1 = CreateObjectSet<cf.Entities.MessagePartyStatus>("MessagePartyStatus1")); }
        }
        private ObjectSet<cf.Entities.MessagePartyStatus> _messagePartyStatus1;

        public ObjectSet<cf.Entities.Message> Messages
        {
            get { return _messages ?? (_messages = CreateObjectSet<cf.Entities.Message>("Messages")); }
        }
        private ObjectSet<cf.Entities.Message> _messages;

        public ObjectSet<cf.Entities.Setter> Setters
        {
            get { return _setters ?? (_setters = CreateObjectSet<cf.Entities.Setter>("Setters")); }
        }
        private ObjectSet<cf.Entities.Setter> _setters;


        #endregion
    }
}
